"""empty message

Revision ID: 82796beb3351
Revises: 78364beee1f2
Create Date: 2025-08-31 23:16:05.324032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82796beb3351'
down_revision = '78364beee1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False, unique=True))
    op.create_unique_constraint("email", 'users', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
