"""empty message

Revision ID: 82796beb3351
Revises: 78364beee1f2
Create Date: 2025-08-31 23:16:05.324032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82796beb3351'
down_revision = '78364beee1f2'
branch_labels = None
depends_on = None


def upgrade():
    # 1) add column as NULLable so the ALTER TABLE succeeds
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))

    # 2) backfill existing rows with a unique placeholder per row
    op.execute("""
        UPDATE users
        SET email = username || '+' || id::text || '@example.local'
        WHERE email IS NULL
    """)

    # 3) now enforce NOT NULL
    op.alter_column('users', 'email', nullable=False)

    # 4) (recommended) add a unique constraint at the DB level
    op.create_unique_constraint('uq_users_email', 'users', ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
