services:
  api:
    ports:
      - "5678:5678"   # debugger port, in addition to 5050 from base
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      FLASK_APP: app.py
    command:
      - python
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5678
      - --wait-for-client
      - -m
      - flask
      - run
      - --no-reload
      - --host=0.0.0.0
      - --port=5050
