services:
  api:
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      FLASK_APP: app.py
    command: ["python","-m","flask","run","--host=0.0.0.0","--port=5050","--reload"]
