FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .
ENV FLASK_APP=app.py
EXPOSE 5050
CMD ["/bin/bash", "docker-entrypoint.sh"]